### ISSUE TITLE
bitbake rpi-hwup-image-rt -c populate_sdk_ext fails

### ISSUE THREAD

**Issue by voltamund** [s-vincent/meta-raspberrypi-rt-sv#1]
When I try to generate an extensible SDK I get this error:
Parsing recipes...ERROR: ParseError at /home/user/yocto/rpi/poky/build-rpi-rt/tmp/work/raspberrypi3-poky-linux-gnueabi/rpi-hwup-image-rt/1.0-r0/sdk-ext/image/tmp-renamed-sdk/layers/poky/meta-raspberrypi-rt-sv/recipes-kernel/linux/linux-raspberrypi-rt-dev.bb:19: **Could not include required file** /home/user/yocto/rpi/poky/build-rpi-rt/tmp/work/raspberrypi3-poky-linux-gnueabi/rpi-hwup-image-rt/1.0-r0/sdk-ext/image/tmp-renamed-sdk/../meta-raspberrypi/recipes-kernel/linux/**linux-raspberrypi.inc**

I changed the 3 linux-raspberrypi-rt recipes and used
`require recipes-kernel/linux/linux-raspberrypi.inc`
instead of
`require ${TOPDIR}/../meta-raspberrypi/recipes-kernel/linux/linux-raspberrypi.inc`

After this change populate_sdk_ext succeeded.

**Comment by s-vincent** [comment]
Thank you for the report :).

I will look at it.

**Comment by s-vincent** [comment]
Fix in revision f70ac44b311adcd19d8da95186bd8141f1230a78.
